### ISSUE TITLE
Running the quickstart example gives error

### ISSUE THREAD

**Issue by ayushh2k** [Not-Diamond/notdiamond-node#44]
While running the [quickstart example](https://docs.notdiamond.ai/docs/quickstart) with `gemini-1.5-flash-latest` i get the following error:
```
file:///home/notdiamond/node_modules/notdiamond/dist/index.mjs:625
      providers[0],
               ^

TypeError: Cannot read properties of undefined (reading '0')
    at NotDiamond.acreate (file:///home/notdiamond/node_modules/notdiamond/dist/index.mjs:625:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/notdiamond/test.js:9:16

Node.js v18.20.4
```

Code:

```
import { NotDiamond } from 'notdiamond';
import dotenv from 'dotenv';
dotenv.config();

// Initialize the Not Diamond client
const notDiamond = new NotDiamond();

// The best LLM is determined by Not Diamond based on the messages and specified models
const result = await notDiamond.create({
  messages: [
    { role: 'system', content: 'You are a world class programmer.' },
    { role: 'user', content: 'Consiely explain merge sort.' }  // Adjust as desired
  ],
  llmProviders: [
    { provider: 'google', model: 'gemini-1.5-flash-latest'}
  ]
});

if ('detail' in result) {
  console.error('Error:', result.detail);
} 
else {
  console.log('Not Diamond session ID:', result.session_id);  // A unique ID of Not Diamond's recommendation
  console.log('LLM called:', result.providers);  // The LLM routed to
  console.log('LLM output', result.content); // The LLM response
}
```

npm package version: `1.0.9`

**Comment by ayushh2k** [comment]
After a few retries it gave the `code error: 'CERTIFICATE_EXPIRED' and started working again, im closing the issue
